resources:
  - name: myScannedRepo
    type: GitRepo
    configuration:
      # SCM integration where the repository is located
      gitProvider: "github_integration" 
      # Repository path, including org name/repo name
      path: "barlesh/jfrog-pipelines-simple-example"
      branches:
        # Specifies which branches will trigger dependent steps
        include: master


pipelines:
  - name: SpectralProtection
    steps:
      - name: SpectralScan
        type: Bash
        configuration:
            integrations:
                - name: spectraldsn
            inputResources:
                # Sets up step to be triggered when there are commit events to myFirstRepo
                - name: myScannedRepo
        execution:
          onExecute:
            - cd dependencyState/resources/myScannedRepo
            - curl -L "https://get.spectralops.io/latest/x/sh?dsn=$int_spectraldsn_SPECTRAL_DSN" | sh
            - $HOME/.spectral/spectral scan --dsn $int_spectraldsn_SPECTRAL_DSN

