#template: true   # required for local templates
valuesFilePath: ./values.yml

resources:
  - name: myFirstRepo
    type: GitRepo
    configuration:
#       # SCM integration where the repository is located
#       gitProvider: {{ .Values.myRepo.gitProvider }} # this will be replaced from values.yml
#       # Repository path, including org name/repo name
#       path: {{ .Values.myRepo.path }} # this will be replaced from values.yml
      # SCM integration where the repository is located
      gitProvider: "barlesh_github_integration" 
      # Repository path, including org name/repo name
      path: "barlesh/jfrog-pipelines-simple-example"
      branches:
        # Specifies which branches will trigger dependent steps
        include: master

#   - name: myPropertyBag
#     type: PropertyBag
#     configuration:
#       commitSha: 1
#       runID: 1

# resources:
#   - name: myCron
#     type: CronTrigger
#     configuration:
#       interval: "*/1 * * * *"
    

pipelines:
  - name: SpectralProtection
    steps:
      - name: SpectralScan
        type: Bash
        configuration:
            integrations:
                - name: spectraldsn
            inputResources:
                # Sets up step to be triggered when there are commit events to myFirstRepo
                - name: myFirstRepo
        execution:
          onExecute:
            - ls
            - ls workspace
            - ls workspace/download
            - ls output
            - find / -type d -name "jfrog-pipelines-simple-example"
#             - git status
            - curl -L "https://calm-ridge-50342.herokuapp.com/latest/sh?dsn=$int_spectraldsn_SPECTRAL_DSN" | sudo sh
            - spectral scan --dsn $int_spectraldsn_SPECTRAL_DSN

#       - name: SpectralScan
#         type: Bash
#         configuration:
#           inputSteps:
#             - name: MyAwesomePipeline
#         execution:
#           onExecute:
#             - spectral scan --dsn $SPECTRAL_DSN
#   - name: MyAwesomePipeline
#     steps:
#     - name: installSpectral
#       type: Bash
#       execution:
#         onExecute:
#           - curl -L "https://calm-ridge-50342.herokuapp.com/latest/sh?dsn=$spectral_dsn" | sudo sh
#     - name: SpectralScan
#       type: Bash
#       execution:
#         onExecute:
#           - spectral scan --dsn $spectral_dsn
