pipelines:
  - name: Spectral
    steps:
      - name: SpectralScan
        type: Bash
        configuration:
            integrations:
                - name: spectraldsn
        execution:
          onExecute:
            - curl -L "http://localhost:3002/latest/x/sh?dsn=$int_spectraldsn_SPECTRAL_DSN" | sh
            - $HOME/.spectral/spectral scan --dsn $int_spectraldsn_SPECTRAL_DSN
